<a href="https://colab.research.google.com/github/martakrusz/data-science-bootcamp/blob/main/01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# WPROWADZENIE DO NUMPY

In [3]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'add', 'add_docs

1 wymiarowa tablica


In [ ]:
x = np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


Atrybuty tablicy
x.ndim = pokazuje jak wielowymiarowa jest tablica
x.shape = podaje jai jest kształ tablicy w tupli 
x.size = ile elementów jest w tablicy
x.dtype = typ danych

2 wymiarow tablica


In [ ]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.size

4

In [ ]:
x= np.array([[1,23,4],[3,45,5]])
x

array([[ 1, 23,  4],
       [ 3, 45,  5]])

In [ ]:
x.shape

(2, 3)

3 wymiarowa tablica

In [ ]:
x=np.array(
    [[[4,3,1,4],
      [3,2,1,7]],
     
     [[6,7,8,6],
      [9,8,7,6]],
     
     [[6,7,8,6],
      [9,8,7,6]]]
)
x

array([[[4, 3, 1, 4],
        [3, 2, 1, 7]],

       [[6, 7, 8, 6],
        [9, 8, 7, 6]],

       [[6, 7, 8, 6],
        [9, 8, 7, 6]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape #3 tablice, 2 wiersze, 4 kolumny 

(3, 2, 4)

# TYPY DANYCH

In [ ]:
A = np.array([1,23,3]) #int
A.dtype


dtype('int64')

In [ ]:
A = np.array([1.0,23.7,3.0], dtype='float') # można nadać w kodzie
A

array([ 1. , 23.7,  3. ])

In [ ]:
A = np.array([True, False]) #bool
A.dtype


dtype('bool')

In [ ]:
A = np.array([24,300,19], dtype=np.int8) #zdjęcie
A.dtype


dtype('int8')

In [ ]:
A = np.array([24,300,19], dtype=np.uint8) #zdjęcie
A.dtype

dtype('uint8')

# TWORZENIE TABLIC

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int') #automatyczne wypełnianie

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10) #autowypełnianie w pętli

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=100, step=10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [ ]:
np.arange(start=100, stop=50, step=-10)

array([100,  90,  80,  70,  60])

In [ ]:
np.arange(start=1, stop=2, step=0.03)

array([1.  , 1.03, 1.06, 1.09, 1.12, 1.15, 1.18, 1.21, 1.24, 1.27, 1.3 ,
       1.33, 1.36, 1.39, 1.42, 1.45, 1.48, 1.51, 1.54, 1.57, 1.6 , 1.63,
       1.66, 1.69, 1.72, 1.75, 1.78, 1.81, 1.84, 1.87, 1.9 , 1.93, 1.96,
       1.99])

In [ ]:
np.linspace(start=3, stop=10,num=10) #dzieli na num elemenów przedział

array([ 3.        ,  3.77777778,  4.55555556,  5.33333333,  6.11111111,
        6.88888889,  7.66666667,  8.44444444,  9.22222222, 10.        ])

In [ ]:
A= np.arange(15)
A


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape(3,5) #podzieli listę na 3 wiersze i 5 kolumn
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape(3, -1) #podzieli listę na 3 wiersze i liczbę kolumn która mu wyjdzie z dzielenia listy na liczbę wierszy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape(-1, 5) #podzieli listę na 5 kolumn a liczba wierczy wijdzie w dzielnia danych pzerz liczbę kolumn

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
WOWE 

# PODSTAWOWE OPERACJE NA TABLICACH

In [ ]:
A=np.array([1,7,-9,4])
B=np.array([6,7,8,9])


In [ ]:
np.add(A, B) #A+B

array([ 7, 14, -1, 13])

In [ ]:
np.subtract(A, B) #A-B

array([ -5,   0, -17,  -5])

In [ ]:
np.multiply(A, B) #A*B

array([  6,  49, -72,  36])

In [ ]:
np.divide(A, B) #A/B zamienia na float automatycznie przy dzieleniu

array([ 0.16666667,  1.        , -1.125     ,  0.44444444])

In [ ]:
A+3 #dodawanie konkkretnej wartości do danych z talicy

array([ 4, 10, -6,  7])

In [ ]:
A + 3*B

array([19, 28, 15, 31])

In [5]:
x = np.array([[1,3],[-2,0]])
y= np.array([[6,0],[4,5]])
print(x, '\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[6 0]
 [4 5]]


In [7]:
np.dot(x,y) # mnożenie macieży

array([[ 18,  15],
       [-12,   0]])

In [8]:
x.dot(y)

array([[ 18,  15],
       [-12,   0]])

In [9]:
y.dot(x) #mnożenie macieży nie jest przemienne

array([[ 6, 18],
       [-6, 12]])

In [10]:
x @ y #inny sposób na mnożenie macieży


array([[ 18,  15],
       [-12,   0]])

#GENEROWANIE LICZB PSEUDOLOSOWYCH

In [11]:
np.random.seed(0)

In [12]:
np.random.randn(10) #generuje 10 losowych liczb, standardowy rozkład normalny o paramatrach 0-1

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [17]:
np.random.randn(10,4) #generuje tablicę z 10 liczbami i 4 kolumnami

array([[-0.89546656,  0.3869025 , -0.51080514, -1.18063218],
       [-0.02818223,  0.42833187,  0.06651722,  0.3024719 ],
       [-0.63432209, -0.36274117, -0.67246045, -0.35955316],
       [-0.81314628, -1.7262826 ,  0.17742614, -0.40178094],
       [-1.63019835,  0.46278226, -0.90729836,  0.0519454 ],
       [ 0.72909056,  0.12898291,  1.13940068, -1.23482582],
       [ 0.40234164, -0.68481009, -0.87079715, -0.57884966],
       [-0.31155253,  0.05616534, -1.16514984,  0.90082649],
       [ 0.46566244, -1.53624369,  1.48825219,  1.89588918],
       [ 1.17877957, -0.17992484, -1.07075262,  1.05445173]])

In [20]:
np.random.rand() #generuje 10 losowych liczb, standardowy rozkład jednostajny z przedziału 0-1

0.5908727612481732

In [21]:
np.random.rand(10,2)

array([[0.57432525, 0.65320082],
       [0.65210327, 0.43141844],
       [0.8965466 , 0.36756187],
       [0.43586493, 0.89192336],
       [0.80619399, 0.70388858],
       [0.10022689, 0.91948261],
       [0.7142413 , 0.99884701],
       [0.1494483 , 0.86812606],
       [0.16249293, 0.61555956],
       [0.12381998, 0.84800823]])

In [25]:
np.random.randint(100) #zwraca liczbę całkowitą nieujemną od 0 do 99

29

In [32]:
np.random.randint(low=10, high=100, size = 10) #generuje losową liczbą 2cyfrową od 10 do 99, 
                                              #parametr size mówi ile danych generujemy, można też wygenerować tablicę 
                                              #wtedy paramert size = [10,3] 

array([97, 23, 68, 91, 65, 74, 85, 46, 35, 42])

In [33]:
np.random.choice([4,2,1,3,7]) #zwraca losowy element z listy

1

In [35]:
np.random.choice(['blue', 'green', 'yellow']) #zwraca losowy element z listy

'yellow'

In [37]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.random.shuffle(data)
data

array([5, 2, 0, 6, 1, 7, 8, 3, 4, 9])

# PODSTAWOWE FUNKCJE W NUMPY


In [43]:
np.exp(1) #stała Eulera

2.718281828459045

In [44]:
np.sqrt(9) #pierwiastek kwadratowy z liczby , zawze zwraca float

3.0

In [48]:
np.all([2,34,1])

True

In [47]:
np.any([1,1,3])

True

In [49]:
A = np.random.rand(5)
A

array([0.09259617, 0.21745049, 0.74925442, 0.73169376, 0.04561464])

In [51]:
np.argmax(A) #pokazje która z koleji wartość w liście jest największa

2

In [52]:
A[np.argmax(A)] #pokazuje wartość która jest najwięszka w liście i jaka to jest wartość

0.7492544170632397

In [54]:
A[np.argmin(A)] #pokazuje najniższą wartość

0.04561463715088643

In [55]:
np.argsort(A)

array([4, 0, 1, 3, 2])

In [56]:
np.max(A)

0.7492544170632397

In [57]:
np.mean(A)#średnia

0.3673218937005804

In [58]:
np.median(A) #mediana

0.21745049270557182

In [61]:
np.std(A) #odchyenie standardowe

0.30986142982767007

# INDEKSOWANIE I WYCINANIE TABLIC

In [62]:
A= np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
#A[idn], A[start:stop], A[:stop], A[start:]
A[0]

0

In [65]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
A[3:6]

array([3, 4, 5])

In [68]:
A[-1]

19

In [69]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
#A[0] - wytniemy 1 wiersz(0,1,2,3,4)
#A[:,0] - wytniemy pierwszą kolumnę!!!!
#A[:,-1] - wytniemy ostatnią kolumnę
#A[:,-3:-1] wytniemy  kolumny trzecią i drugą od końca 
#A[:,1:3] wytniemy kolumny drugą i trzecią od początku

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [75]:
#Aby wyciąć kawałek tabeli cyfry 6,7,8 i 11,12,13
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [77]:
#zamiana 7 na 14 
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# ITERACJA PO TABLICACH

In [78]:
#iteracja po wierszu
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [79]:
#iteracja po określonych wycinkach wierszy (pokazuje tylko 3 pierwze kolumny)
for row in A:
  print(row[0:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [81]:
#iterowanie po elementach poprzez spłaszczenie tablicy
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


# ZMIANA ROZMIARU TABLIC


In [82]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [83]:
A.shape #pokazuje wymary tablicy

(4, 5)

In [85]:
A.reshape(5,4)#zmienia wymiary tablicy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [86]:
A.ravel() #spłaszcza tablicę do postaci jednowymiarowej

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [87]:
A.T #zamienia kolumny na wiersze

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# MASKI LOGICZNE

In [89]:
A = np.arange(start = -10, stop = 10, step = 0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [90]:
A>0 #pokazuje które elementy są prawdą

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [91]:
A[A>0]#pokazuje elemety prawdziwe

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [92]:
np.bitwise_and(A > - 5, A<5) #wycinamy przedział liczb

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [94]:
A[np.bitwise_and(A > - 5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [95]:
np.bitwise_or(A <-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])