<a href="https://colab.research.google.com/github/martakrusz/data-science-bootcamp/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# WPROWADZENIE DO NUMPY

In [4]:
import numpy as np
np.__version__

'1.19.5'

In [5]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'add', 'add_docs

1 wymiarowa tablica


In [6]:
x = np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


Atrybuty tablicy
x.ndim = pokazuje jak wielowymiarowa jest tablica
x.shape = podaje jai jest kształ tablicy w tupli 
x.size = ile elementów jest w tablicy
x.dtype = typ danych

2 wymiarow tablica


In [ ]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.size

4

In [ ]:
x= np.array([[1,23,4],[3,45,5]])
x

array([[ 1, 23,  4],
       [ 3, 45,  5]])

In [ ]:
x.shape

(2, 3)

3 wymiarowa tablica

In [ ]:
x=np.array(
    [[[4,3,1,4],
      [3,2,1,7]],
     
     [[6,7,8,6],
      [9,8,7,6]],
     
     [[6,7,8,6],
      [9,8,7,6]]]
)
x

array([[[4, 3, 1, 4],
        [3, 2, 1, 7]],

       [[6, 7, 8, 6],
        [9, 8, 7, 6]],

       [[6, 7, 8, 6],
        [9, 8, 7, 6]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape #3 tablice, 2 wiersze, 4 kolumny 

(3, 2, 4)

# TYPY DANYCH

In [33]:
A = np.array([1,23,3]) #int
A.dtype


dtype('int64')

In [38]:
A = np.array([1.0,23.7,3.0], dtype='float') # można nadać w kodzie
A

array([ 1. , 23.7,  3. ])

In [39]:
A = np.array([True, False]) #bool
A.dtype


dtype('bool')

In [41]:
A = np.array([24,300,19], dtype=np.int8) #zdjęcie
A.dtype


dtype('int8')

In [42]:
A = np.array([24,300,19], dtype=np.uint8) #zdjęcie
A.dtype

dtype('uint8')

# TWORZENIE TABLIC

In [43]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [47]:
np.ones(shape=(4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full(shape=(3, 3), fill_value=4, dtype='int') #automatyczne wypełnianie

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [9]:
np.arange(10) #autowypełnianie w pętli

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(start=5, stop=100, step=10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [13]:
np.arange(start=100, stop=50, step=-10)

array([100,  90,  80,  70,  60])

In [14]:
np.arange(start=1, stop=2, step=0.03)

array([1.  , 1.03, 1.06, 1.09, 1.12, 1.15, 1.18, 1.21, 1.24, 1.27, 1.3 ,
       1.33, 1.36, 1.39, 1.42, 1.45, 1.48, 1.51, 1.54, 1.57, 1.6 , 1.63,
       1.66, 1.69, 1.72, 1.75, 1.78, 1.81, 1.84, 1.87, 1.9 , 1.93, 1.96,
       1.99])

In [19]:
np.linspace(start=3, stop=10,num=10) #dzieli na num elemenów przedział

array([ 3.        ,  3.77777778,  4.55555556,  5.33333333,  6.11111111,
        6.88888889,  7.66666667,  8.44444444,  9.22222222, 10.        ])

In [20]:
A= np.arange(15)
A


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
A.reshape(3,5) #podzieli listę na 3 wiersze i 5 kolumn
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
A.reshape(3, -1) #podzieli listę na 3 wiersze i liczbę kolumn która mu wyjdzie z dzielenia listy na liczbę wierszy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
A.reshape(-1, 5) #podzieli listę na 5 kolumn a liczba wierczy wijdzie w dzielnia danych pzerz liczbę kolumn

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
WOWE 

# PODSTAWOWE OPERACJE NA TABLICACH

In [35]:
A=np.array([1,7,-9,4])
B=np.array([6,7,8,9])


In [45]:
np.add(A, B) #A+B

array([ 7, 14, -1, 13])

In [46]:
np.subtract(A, B) #A-B

array([ -5,   0, -17,  -5])

In [47]:
np.multiply(A, B) #A*B

array([  6,  49, -72,  36])

In [50]:
np.divide(A, B) #A/B zamienia na float automatycznie przy dzieleniu

array([ 0.16666667,  1.        , -1.125     ,  0.44444444])

In [40]:
A+3 #dodawanie konkkretnej wartości do danych z talicy

array([ 4, 10, -6,  7])

In [44]:
A + 3*B

array([19, 28, 15, 31])