<a href="https://colab.research.google.com/github/martakrusz/data-science-bootcamp/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# WPROWADZENIE DO NUMPY

In [ ]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
print(dir(np))

1 wymiarowa tablica


In [ ]:
x = np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


Atrybuty tablicy
x.ndim = pokazuje jak wielowymiarowa jest tablica
x.shape = podaje jai jest kształ tablicy w tupli 
x.size = ile elementów jest w tablicy
x.dtype = typ danych

2 wymiarow tablica


In [ ]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.size

4

In [ ]:
x= np.array([[1,23,4],[3,45,5]])
x

array([[ 1, 23,  4],
       [ 3, 45,  5]])

In [ ]:
x.shape

(2, 3)

3 wymiarowa tablica

In [ ]:
x=np.array(
    [[[4,3,1,4],
      [3,2,1,7]],
     
     [[6,7,8,6],
      [9,8,7,6]],
     
     [[6,7,8,6],
      [9,8,7,6]]]
)
x

array([[[4, 3, 1, 4],
        [3, 2, 1, 7]],

       [[6, 7, 8, 6],
        [9, 8, 7, 6]],

       [[6, 7, 8, 6],
        [9, 8, 7, 6]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape #3 tablice, 2 wiersze, 4 kolumny 

(3, 2, 4)

# TYPY DANYCH